import {
  BadgeDollarSign,
  ChartNoAxesCombined,
  ClipboardCheck,
  Mail,
  Megaphone,
  MonitorSmartphone,
  NotebookPen,
  Pill,
  ShoppingBag,
  Store,
  Users,
  Database,
  Sparkles,
} from "lucide-react";

export const solutions = [
  {
    title: "Built for Growth Teams",
    description: "One trusted partner for marketing, operations, development, and support.",
    image: "/images/a-sleek-ai-powered-virtual-assistant-hologram-proj (1)-min.png",
    icon: Sparkles,
    theme: "dark",
    size: "tall",
  },
  {
    title: "Google Ads",
    description: "Certified experts to scale PPC campaigns and maximize ROAS.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    icon: Megaphone,
    theme: "light",
    size: "standard",
  },
  {
    title: "Meta Ads",
    description: "Facebook and Instagram ads that convert audiences into customers.",
    image: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=800&q=80",
    icon: BadgeDollarSign,
    theme: "light",
    size: "standard",
  },
  {
    title: "Digital Marketing",
    description: "Full-funnel strategies to grow brand visibility and demand generation.",
    image: "https://images.unsplash.com/photo-1557838923-2985c318be48?auto=format&fit=crop&w=800&q=80",
    icon: ChartNoAxesCombined,
    theme: "light",
    size: "wide",
  },
  {
    title: "Email Marketing",
    description: "Automated campaigns and newsletters that nurture loyal customers.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
    icon: Mail,
    theme: "dark",
    size: "standard",
  },
  {
    title: "Social Media",
    description: "Content, community, and growth across every major platform.",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80",
    icon: Users,
    theme: "light",
    size: "wide",
  },
  {
    title: "Lead Generation",
    description: "Qualified leads delivered through research-driven outreach.",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=800&q=80",
    icon: ClipboardCheck,
    theme: "light",
    size: "standard",
  },
  {
    title: "Amazon Experts",
    description: "Listing optimization, ads, and account management for Amazon sellers.",
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
    icon: ShoppingBag,
    theme: "dark",
    size: "tall",
  },
  {
    title: "Walmart Experts",
    description: "Marketplace specialists for Walmart growth and operations.",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80",
    icon: Store,
    theme: "light",
    size: "standard",
  },
  {
    title: "Shopify Developers",
    description: "Custom storefronts, integrations, and performance optimization.",
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
    icon: Store,
    theme: "light",
    size: "wide",
  },
  {
    title: "WordPress Developers",
    description: "Secure, scalable WordPress sites built for speed and SEO.",
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&w=800&q=80",
    icon: NotebookPen,
    theme: "light",
    size: "standard",
  },
  {
    title: "Mobile App Development",
    description: "Native and cross-platform apps from concept to launch.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80",
    icon: MonitorSmartphone,
    theme: "dark",
    size: "standard",
  },
  {
    title: "Data Entry",
    description: "Accurate, high-volume data processing with fast turnaround.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    icon: Database,
    theme: "light",
    size: "standard",
  },
  {
    title: "Medical Processes",
    description: "Billing, coding, and admin support for healthcare teams.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    icon: Pill,
    theme: "light",
    size: "wide",
  },
  {
    title: "Public Relations",
    description: "Media outreach and brand storytelling that builds authority.",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80",
    icon: Users,
    theme: "dark",
    size: "standard",
  },
  {
    title: "Real Estate",
    description: "Virtual assistants for listings, CRM, and client coordination.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80",
    icon: Users,
    theme: "light",
    size: "standard",
  },
  {
    title: "Power BI",
    description: "Dashboards and analytics that turn data into decisions.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    icon: ChartNoAxesCombined,
    theme: "light",
    size: "wide",
  },
];
