export const countries = [
  { label: "USA", code: "+1" },
  { label: "UK", code: "+44" },
  { label: "Canada", code: "+1" },
  { label: "Australia", code: "+61" },
  { label: "Germany", code: "+49" },
  { label: "France", code: "+33" },
  { label: "Singapore", code: "+65" },
  { label: "UAE", code: "+971" },
  { label: "New Zealand", code: "+64" },
  { label: "Saudi Arabia", code: "+966" },
  { label: "India", code: "+91" },
  { label: "Japan", code: "+81" },
  { label: "South Africa", code: "+27" },
  { label: "Brazil", code: "+55" },
  { label: "Mexico", code: "+52" },
  { label: "Philippines", code: "+63" },
  { label: "Netherlands", code: "+31" },
  { label: "Switzerland", code: "+41" },
  { label: "Ireland", code: "+353" },
  { label: "Italy", code: "+39" },
  { label: "Spain", code: "+34" },
  { label: "Sweden", code: "+46" },
  { label: "Norway", code: "+47" },
  { label: "Denmark", code: "+45" },
  { label: "Belgium", code: "+32" },
  { label: "Poland", code: "+48" },
  { label: "Turkey", code: "+90" },
  { label: "Israel", code: "+972" },
  { label: "Malaysia", code: "+60" },
  { label: "Hong Kong", code: "+852" },
];
